### ISSUE TITLE
node examples does not work when run more than once

### ISSUE THREAD

**Issue by sergiuchuckmisha** [soniox/soniox_examples#2]
when running sample files such as: 
`transcribe_file_async.js`
`transcribe_file_async_separate_recognition.js`
`transcribe_file_short.js`
`transcribe_file_short_separate_recognition.js`
`transcribe_stream_separate_recognition.js`
with default code, only added `api_key` no useful output in the console; only "Uploading file."

way to run: 
`node transcribe_file_short.js`
env: tried both `Node.js v18.16.0` and node version `20.2.0`

**Comment by klemensimonic2** [comment]
Please follow the steps provided in our [Quickstart](https://soniox.com/docs/quickstart/index.html) tutorial and you will be able to correctly and successfully use Soniox.

Note, if you are using node.js v14 or higher is required. You can check the node version by `node --version`
