### ISSUE TITLE
"After. You shared awareness." audio transcribing does not work on paid plan. service just returns: "After. You shared awareness."

### ISSUE THREAD

**Issue by sergiuchuckmisha** [soniox/soniox_examples#4]
how to reproduce: 
- put 5 hours Russian speaking audio file into `test_data` folder
- change code of `transcribe_file_stream.py` file to use above audio file
- run `python % python3 transcribe_file_stream.py`
python version: `python % python3 --version                
Python 3.11.3`

expected result: speech recognition
actual result: `After. You shared awareness.` in the console output

**Comment by sergiuchuckmisha** [comment]
![image](https://github.com/soniox/soniox_examples/assets/7792816/dc9ba9b2-2a6d-4aff-a93b-ab88932eaa5f)

**Comment by klemensimonic2** [comment]
To transcribe files, I would recommend to follow our [Transcribe Files](https://soniox.com/docs/how-to-guides/transcribe-audio/transcribe-files.html) tutorial.

Also, please check supported [Models and Languages](https://soniox.com/docs/how-to-guides/models-and-languages/index.html).
